version: '3.3'

services:

  elastic:
    image: elasticsearch:7.2.0
    hostname: elastic
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.2.0
    hostname: kibana
    depends_on:
      - elastic
    links:
      - elastic
    expose:
      - "5601"
    ports:
      - "5601:5601"
    environment:
      - "SERVER.NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://elastic:9200"